group 'com.danieldallos.storeredirect'
version '1.0-SNAPSHOT'

apply plugin: 'com.android.library'

android {
    namespace "com.danieldallos.storeredirect"

    compileSdkVersion 34

    defaultConfig {
        minSdkVersion 21
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    // Java 17 without --release
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        disable 'InvalidPackage'
    }
}

repositories {
    google()
    mavenCentral()
}
